#!/bin/bash

source "$(dirname $(readlink $BASH_SOURCE))/../os/utils.sh" \
    && declare OS="$(get_os)"

# ----------------------------------------------------------------------
# | Navigation                                                         |
# ----------------------------------------------------------------------

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias cd..='cd ..'

# ----------------------------------------------------------------------
# | Network                                                            |
# ----------------------------------------------------------------------

alias ip='dig +short myip.opendns.com @resolver1.opendns.com'

# ----------------------------------------------------------------------
# | Package Managers                                                   |
# ----------------------------------------------------------------------

# OS specific package managers

if [ "$OS" == 'ubuntu' ]; then

    # Advanced Packaging Tool
    alias apti='sudo apt-get install'
    alias aptr='sudo apt-get remove'
    alias apts='sudo apt-cache search'
    alias aptu='sudo apt-get update \
                 && sudo apt-get upgrade'

fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Update



if [ "$OS" == 'ubuntu' ]; then

    alias u='sudo apt-get update \
                && sudo apt-get upgrade \
                && npm install -g npm \
                && npm upgrade -g'

fi

# ----------------------------------------------------------------------
# | Shorter Commands                                                   |
# ----------------------------------------------------------------------

alias :q='exit'
alias c='clear'
alias ch='history -c && > ~/.bash_history'
alias e='vim'
alias g='git'
alias ll='ls -l'
alias m='man'
alias map='xargs -n1'
alias n='npm'
alias q='exit'
alias rm='rm -rf'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Copy to clipboard

if [ "$OS" == 'ubuntu' ]; then
    alias cc='xclip -selection clip'
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Hide/Show files
if [ "$OS" == 'ubuntu' ]; then

    # Hide/Show desktop icons
    alias hide-desktop-icons='gsettings set org.gnome.desktop.background show-desktop-icons false'
    alias show-desktop-icons='gsettings set org.gnome.desktop.background show-desktop-icons true'

fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Lock screen

if [ "$OS" == 'ubuntu' ]; then
    alias akf='gnome-screensaver-command --lock'
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Open

if [ "$OS" == 'ubuntu' ]; then
    alias o='xdg-open'
fi

# ----------------------------------------------------------------------

# Unset anything that just pollutes the global space

unset OS
